### ISSUE TITLE
different interfaces when adding data types to user and master libraries

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1267]
The user interfaces are different when adding an HL7 data type to either a user or master library. The "versions" column in the master library interface is helpful but why doesn't it have the options of "as is" or "as flavor" like the user library does? Is there something fundamentally difference about user and master libraries that requires these differences? I have the impression that the only real diffference in data types is who can access them (all users should have access to the master libraries but user libraries are user specific).

Also note that the column headers are a bit different in the Selected Data Types section.

![image](https://cloud.githubusercontent.com/assets/17408249/22992616/de7ede44-f385-11e6-9d15-d97141f6066e.png)

![image](https://cloud.githubusercontent.com/assets/17408249/22992704/1d947260-f386-11e6-9564-5cafa88680b7.png)

**Comment by csnewman88** [comment]
Similar differences exist when adding master and user library data types to an IG. In particular, there isn't a way to add a master library data type "as is" which seems crucial. This leads to an oddity where the imported data type is labeled USR but the value set used by the data type is labeled MAS.

![image](https://cloud.githubusercontent.com/assets/17408249/22993903/56b6d282-f38a-11e6-990a-7fe44e9905b4.png)

![image](https://cloud.githubusercontent.com/assets/17408249/22993928/74a1a754-f38a-11e6-9935-431c56871f0b.png)

**Comment by Abdelghani90** [comment]
Creating a Master datatype is different than creating a User one. 
For the Master datatype you can only create a flavor, the list of versions I shows the versions where the datatype did not change. 
If the user wants to create a master datatype, he should first select the HL7 Version then the list of versions will be filtered  based on the HL7 version he selected. 
When he the user select a datatype, I create a flavor based on the HL7 version he selected.
After that the user can modify the datatype and publish it and import it an IgDocument or an other datatype Library. 

In case of He import it to an IG document: 
He can only import it as a Flavor and the HL7 version of the IG document will be affected to this datatype. He will have a user datatype, with the same content of Master one he imported, but with the same version of the IG document.

In case of He import it to a user datatype Library : 
Since a datatype Library has no version, he will have another view where he can select which version he wants to use for this Master.

**Comment by csnewman88** [comment]
I would argue that a Master Library is more useful when the data type flavors can be used in IGs for different base versions so long as the flavor is valid for the base version. That way, the master library curator doesn't need to create multiple identical flavor, one for each version. As well, if an IG changes versions from one release to another, the data types don't necessarily have to change (unless the underlying data type has changes (such as CWE from 2.5.1 to 2.8.2 for example).

I think it might make more sense to first select a data type and then select which variant of the data type to add to the library. It might look something like this:

![image](https://cloud.githubusercontent.com/assets/17408249/22995225/ab3af4a0-f38f-11e6-8610-d666c0915e7d.png)

Then the data type created would apply equally to all valid versions and not just one.

**Comment by robnist** [comment]
Yes, this is what we agreed to and the reason why we did this analysis to find the delta of the DT across the versions. I will make some workflow diagrams to help explain. We will need to meet on this I think,

**Comment by Abdelghani90** [comment]
This will be changed in the next release
