### ISSUE TITLE
OBX-5 (varies) Dynamic mapping must be revisit  

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1365]
Why this is not done in the co-constrain table?  -- Needs discussion.

**Comment by Jungyubw** [comment]
@smartinez290 @robnist @haffo 
As you know, co-constraint is a kind of 'conformance statement'. It is a shortcut for making complex constraints. Dynamic mapping, on the other hand, is a conditional Datatype binding that depends on a specific value (ie OBX.2 or OBX.3). 
Dynamic mapping, on the other hand, is a conditional Datatype binding that depends on a specific value (ie OBX.2 or OBX.3). Most co-constraints are functionally confused with dynamic mapping because they are used in OBX and even OBX-2, OBX-3, and OBX-5 are specified. However, strictly speaking, Co-Constraints can be defined in all Segments, and Dynamic Mapping can be defined only if the Segment has a Field with a "Varies" Datatype.
I do not think it's good to combine the above two into a single UI because their functionality, purpose, and validation method are different.
