### ISSUE TITLE
Clean up usages for segments

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#170]
In the message profile, do all usages apply to segments? How would B, X, C and W be used for segments. If they wouldn't be used for a segment, then that those values should be removed as options.

**Comment by haffonist** [comment]
@robnist any input on this ?

**Comment by haffonist** [comment]
@robnist any input on this ?

**Comment by robnist** [comment]
X and C makes are possible. I believe they are used in the lab order profiles as an FYI.

B and W do not make since as an option. In fact I don't think they make sense at any level. These are only used at the base level to indicate that they are backwards compatibly or withdrawn. I don't see a real case where you would do this in profiling. So remove B and W as options at all levels.

**Comment by robnist** [comment]
Did mean to Close, close, just the dialog.... :<)

**Comment by haffonist** [comment]
ok, thanks

**Comment by Jungyubw** [comment]
Done
