### ISSUE TITLE
difference between a constraint and a predicate??

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1819]
In your mind, is there a distinction between a predicate and a constraint? In the predicate editor in IGAMT Dev, the word "constraint" is used in a variety of places even though it's the predicate editor. Is "constraint" the right word to use here?

![image](https://user-images.githubusercontent.com/17408249/26990908-0681fd94-4d1e-11e7-8776-472f934d02a0.png)

**Comment by Jungyubw** [comment]
@csnewman88 
In my mind, 'Constraint' is a component of 'Conformance Statement' and 'Predicate'. For example, if a constraint, "HD.1 is valued" is used in a conformance statement, this means that the value of HD.1 must be present. However, when used on a Predicate, a Predicate will be completed by adding information such as "Target Node (ex. HD.2)", True Usage (ex. R), and False Usage (ex. X). In other words, the Predicate in the example means "If HD.1 is valued, then HD.2 Usage is 'R' otherwise 'X'."

So the UI is the procedure that completes the predicate by first creating a constraint and then adding True / False Usage information to the next page.

It's used internally for these terms, but it might be different in the HL7 community. Please suggest if you have better logic or terminology. welcome.

Thank you.

**Comment by csnewman88** [comment]
Your explanation makes sense. I think in my mind, I sometimes use constraint and conformance statement interchangeably and that causes me trouble.
