### ISSUE TITLE
can't bind a single value in a data type

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#2304]
Is there a reason why you can only bind a value set and not a single value in a value set in a data type definition? Is this a bug or intentional?

![image](https://user-images.githubusercontent.com/17408249/29565510-dee3ec34-870b-11e7-8464-8fc1b7fd0094.png)

**Comment by csnewman88** [comment]
Doesn't looks like you can do this at the message level either

![image](https://user-images.githubusercontent.com/17408249/29568583-60d8421c-8716-11e7-9c30-3aee48809b82.png)

**Comment by Jungyubw** [comment]
@csnewman88 

Current logic doesn't allow single code for complex Datatype (CQ.2 is CWE).

**Comment by robnist** [comment]
Craig, are you OK with this answer? If so, please close ticket.

**Comment by csnewman88** [comment]
Why is the single code binding limited to simple data types?

**Comment by robnist** [comment]
Because it really doesn't make sense for complex data types. I fear that the specification will be confusing. We may consider finding a solution but the single code element binding is not good.

For complex you have to consider the rest of the DT, what triplet, how is the DT profiled, what about the coding system. These are not issues for the simple data types. Also, in nearly all cases simple DT are HL7 tables, for complex they are mostly external value sets--not that this really matters, but the philosophy in HL7 was to have these simple data type for simple things (sort of self-contained) and have the more complex things for external value sets. 

As mentioned we our considering new capabilities like pairwise binding {A:LN} but sure how to handle the location 1st triplet, etc. Ideas welcomed.
