### ISSUE TITLE
Search Api: No length

### ISSUE THREAD

**Issue by afrold** [haffonist/igamt#2427]
![screen shot 2017-09-13 at 2 38 50 pm](https://user-images.githubusercontent.com/13695248/30394543-5cd01f50-9891-11e7-9b41-a6ee75848902.png)

**Comment by maxence-lefort** [comment]
@haffonist what hl7 version did you export?

**Comment by maxence-lefort** [comment]
@haffonist I don't think this is a bug. Or at least not in the export: each HD's components in 2.8.1 have a length of 0..0, that's why it doesn't show up in the export.

<img width="1220" alt="screen shot 2017-09-21 at 6 24 03 pm" src="https://user-images.githubusercontent.com/13853131/30721501-56962bb0-9efa-11e7-84d4-4155d5f2234f.png">

**Comment by afrold** [comment]
Then let's show 0,0 in the export.


Harold Affo

--------------------------------------------------------------------
The contents of this e-mail and any attachments are intended solely for the use
of the named addressee(s) and may contain confidential and/or privileged
information. Any unauthorized use, copying, disclosure, or distribution of the
contents of this e-mail is strictly prohibited. If you are not the intended
recipient, please notify the sender immediately and delete this email. Thank you.


________________________________
