### ISSUE TITLE
Adding a user data type from a user library -- datatype is not showing

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2698]
Added a data type CWE_USR to "MyDtLib" library:

![image](https://user-images.githubusercontent.com/14842422/33735062-3b27aefa-db5c-11e7-985b-3380e9a44baf.png)

When go to the IG and try the data type from  from "MyDtLib" the data type I created is not listed:

![image](https://user-images.githubusercontent.com/14842422/33734969-eb718d90-db5b-11e7-9292-c5528db82bdd.png)
@Abdelghani90 I did this before and it was working fine.

**Comment by Abdelghani90** [comment]
@smartinez290  this button should be disabled if this datatype is already imported or if the version of the IG or if the version if greater than 2.6

**Comment by smartinez290** [comment]
@Abdelghani90 Thanks. But, I deleted all my DTs from "MyDTlib and the "Derived Data Types" are still displayed. Are they supposed to be removed.? Then, I try to add another data type by right clicking on "MyDTlib" and is not giving me the option to add a datatype. 

![image](https://user-images.githubusercontent.com/14842422/33781417-8bb68a00-dc22-11e7-8683-2491f3d77daf.png)

**Comment by smartinez290** [comment]
This is not a critical issue. We will review it later, specifically how to handle the derived datatypes when the source datatypes are removed from the library.

**Comment by afrold** [comment]
@Abdelghani90

**Comment by Abdelghani90** [comment]
Actually, when  a user delete something, we never delete what is derived from. If you remember, we decided with @robnist to keep them.

**Comment by Abdelghani90** [comment]
I think we decided to keep them with @robnist. you should remove them. those are a separated objects and may be used by many datatypes. We decided to avoid calculating all the references of those objects because we cannot delete them if they have been referenced. 
this is the same logic we use in the IG document. For example, if you delete all the conformance profiles, you will still have the list of the old segments, datatypes and value sets.
