### ISSUE TITLE
Add Definition Text to Conformance Profile

### ISSUE THREAD

**Issue by haffonist** [haffonist/igamt#343]
@Jungyubw 
New requirement from Rob. Please add conformance profile definition text to the model and the existing data.
Please let me know if any question.

Thanks

**Comment by Jungyubw** [comment]
Harold, check this issue.

I have checked UsageNote is already in the message domain and also UI support to edit it at message meta data.

Old converter doesn't have usageNote so converted data has no UsageNote. Because we cannot covert the data again, so we let user know usageNote lost. If user wants to recover the userNote, we should do it one by one.
