### ISSUE TITLE
name vs flavor name in predicate/conformance statements

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#494]
I think using the name instead of the flavor name can be confusing.
![igamt_5](https://cloud.githubusercontent.com/assets/13591511/17569416/207be63e-5f16-11e6-9d9d-02dfaab2b2f2.JPG)

**Comment by Jungyubw** [comment]
I agree to use flavor for Title. but I think it is better for constraint (second circle) to use base name.

Because user can edit the flavor name any time, it is hard to update every CS and CP by changed flavor name. Also Cs and CP exist in the specific Datatype and Segment, so we don't need to use flavor name.

**Comment by carolinerosin** [comment]
I think we'll have to discuss more about that one. I agree that changing the text in the predicate or statement could be a pain, but I think someone that reads the final IG (not the person who wrote everything in IGAMT) could be confused, especially if there are several flavors of the same datatype/segment in the guide. I'll leave the final decision to Rob, but I think we should ask the users that use IGAMT what they think about that.
@robnist Any thoughts ?
