### ISSUE TITLE
Need predicate still at segment level even if I implement a predicate at message level

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#517]
I implemented a predicate at the message level (because it needs access to a value in another segment), but then if I go to my segment, I still get the "Need predicate". See screenshots

![igamt_20](https://cloud.githubusercontent.com/assets/13591511/17593139/e468f73e-5fb2-11e6-990a-ebadea2b10e8.JPG)

![igamt_19](https://cloud.githubusercontent.com/assets/13591511/17593146/e862ef3e-5fb2-11e6-88cc-6647643890a8.JPG)

**Comment by haffonist** [comment]
@Jungyubw we've been talking about this sometimes now, let's implement this.

**Comment by Jungyubw** [comment]
I think this is okay because this means that PID-11 have message level predicate, not segment level. So when the user see the segment at the segment library, the system shows missing predicate, but you can see the message level predicate at the conformance profile view.

The PID flavor could be used for multiple messages (conformance profiles), so this is normal.
