### ISSUE TITLE
export to WORD says [MISSING IMAGE]

### ISSUE THREAD

**Issue by robsavage** [haffonist/igamt#554]
Working on an IG that exports to WORD. I added a jpeg image. Exporting to WORD has message [MISSING IMAGE]. Export to html brings the image.  Also, import into word takes a long time and occasionally hangs. It has a popup that indicates that fields in document point elsewhere and asks to update from links.

**Comment by haffonist** [comment]
Any progress on this ?

**Comment by olivier-m-mr** [comment]
@robsavage : 
The word export does take longer that the html because there is more processing to generate the document. 
The popup that asks to update is a Microsoft "thing". When word detects that there is a table of contents in the document that is being opened for the first time, it parses it to check the content of the TOC. Normally, if you save it and then reopened the file, you should not have the popup. Work around is unfound so far. 
Regarding the long time to generate the word document, we tried to reduce the numbers of calls while generating the document; we added some checks to try to prevent the tool to hang. It can be interesting to know if it happens to you all the time or for a specific IG. 
Regarding the missing image, we are currently trying a solution as it didn't seems to be happening everytime.
