### ISSUE TITLE
Use Craig's Format Style

### ISSUE THREAD

**Issue by haffonist** [haffonist/igamt#867]

**Comment by haffonist** [comment]
@olivier-m-mr as main developer

**Comment by olivier-m-mr** [comment]
Reference documents provided by Craig Newman: 
[HL7-Version-2.8.2-Implementation-Guide--Immunization-Messaging-with-comments-on-formatting.docx](https://github.com/haffonist/igamt/files/642798/HL7-Version-2.8.2-Implementation-Guide--Immunization-Messaging-with-comments-on-formatting.docx)
[HL7-Version-2.8.2-Implementation-Guide-Immunization-Messaging-20171031-for SISC circulation.docx](https://github.com/haffonist/igamt/files/642799/HL7-Version-2.8.2-Implementation-Guide-Immunization-Messaging-20171031-for.SISC.circulation.docx)

**Comment by olivier-m-mr** [comment]
Compiled list of changes & comments: 

1. - [ ] Increase size of font through the document to 10pt
2. - [ ] Remove white space between header and text
3. - [ ] Bold text is not exported as bold and white space after each bolded area is being lost
4. - [ ] Resize figures
5. - [ ] Formatting of “code” in Igamt => no line breaks in export
6. - [ ] Font size of numbers is in list is different that font size of text in numbered list
7. - [ ] White space is lost between code samples
8. - [ ] In the message infrastructure, within the conformance profile section, all the conformance statements are grouped in one table for each profile. The ID column has to be wide enough so that the ID doesn’t wrap.
9. - [ ] Each segment definition contained within a profile is copied into the profile definition section. This means that common segments which are the same between profiles (like MSH) are duplicated, but it also means that each profile section is more stand-alone.
10. - [ ] Characters aren’t translating correctly in the export e.g dashes => â€"
11. - [ ] No more segment and field descriptions (it is moved within profile)
12. - [ ] [comment 13] needs clarification: Optional segments remains is segments and fields description?
13. - [ ] For any optional elements in the segment tables, remove the value set, cardinality and length. Note1: for any optional element, the reader should refer back to the base standard. Note2: in the conformance profile tables, cardinality for optional segments is kept.
14. - [ ] Fields definition texts: add space after semi-colon
15. - [ ] Fields definition texts: remove space between consecutive definition
16. - [ ] Datatype: remove datatype which are not flavours
17. - [ ] Contents  part of value set (highest part) for section is not exported.
18. - [ ] There are a handful of value sets in the export that aren’t in IGAMT. For example, this empty Administrative Sex value is not in IGAMT
19. - [ ] Change “Oid” to “OID”
20. - [ ] Remove “OID: Unspecified” when there is no OID
21. - [ ] Remove value sets that are not specific to immunization

**Comment by olivier-m-mr** [comment]
T1 - Formatting

1  Increase size of font through the document to 10pt
2  Remove white space between header and text
6  Font size of numbers is in list is different that font size of text in numbered list
14 Fields definition texts: add space after semi-colon
15 Fields definition texts: remove space between consecutive definition
19 Change “Oid” to “OID”
20 Remove “OID: Unspecified” when there is no OID


T2 - Content issue

17 Contents part of value set (highest part) for section is not exported.
18 There are a handful of value sets in the export that aren’t in IGAMT. For example, this empty Administrative Sex value is not in IGAMT


T3 - Display issues

3 Bold text is not exported as bold and white space after each bolded area is being lost
4 Resize figures
5 Formatting of “code” in Igamt => no line breaks in export
7 White space is lost between code samples
10 Characters aren’t translating correctly in the export e.g. dashes => â€"


T4 - Content re-organization

8  In the message infrastructure, within the conformance profile section, all the conformance statements are grouped in one table for each profile. The ID column has to be wide enough so that the ID doesn’t wrap.
9 Each segment definition contained within a profile is copied into the profile definition section. This means that common segments which are the same between profiles (like MSH) are duplicated, but it also means that each profile section is more stand-alone. 
11 No more segment and field descriptions (it is moved within profile)
12 [comment 13] needs clarification: should optional segments remains is a separate section?
13 For any optional elements in the segment tables, remove the value set, cardinality and length
Note1: for any optional element, the reader should refer back to the base standard. As a consequence, value set, cardinality and length are removed in segment table.  Note2: in the conformance profile tables, cardinality for optional segments is kept.
16 Datatype: remove datatype which are not flavours
21 Remove value sets that are not specific to immunization
